// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4uzBLe1ACIlqkxMZ1d9-yaivceE8vao',
    appId: '1:992545342972:web:4307c7de07378ac88b5e79',
    messagingSenderId: '992545342972',
    projectId: 'portal-5bd26',
    authDomain: 'portal-5bd26.firebaseapp.com',
    databaseURL: 'https://portal-5bd26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portal-5bd26.firebasestorage.app',
    measurementId: 'G-337YN1HR9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-8RV0nYj3IzaNaQGk3g93fFajt9_R1c',
    appId: '1:992545342972:android:1722fb0e758e70768b5e79',
    messagingSenderId: '992545342972',
    projectId: 'portal-5bd26',
    databaseURL: 'https://portal-5bd26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portal-5bd26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hN3wR8AVMbH7FDb6_NDwA06JXFfnssc',
    appId: '1:992545342972:ios:bdcd5055abd5410b8b5e79',
    messagingSenderId: '992545342972',
    projectId: 'portal-5bd26',
    databaseURL: 'https://portal-5bd26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portal-5bd26.firebasestorage.app',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3hN3wR8AVMbH7FDb6_NDwA06JXFfnssc',
    appId: '1:992545342972:ios:bdcd5055abd5410b8b5e79',
    messagingSenderId: '992545342972',
    projectId: 'portal-5bd26',
    databaseURL: 'https://portal-5bd26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portal-5bd26.firebasestorage.app',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw4uzBLe1ACIlqkxMZ1d9-yaivceE8vao',
    appId: '1:992545342972:web:390659316c4f75648b5e79',
    messagingSenderId: '992545342972',
    projectId: 'portal-5bd26',
    authDomain: 'portal-5bd26.firebaseapp.com',
    databaseURL: 'https://portal-5bd26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portal-5bd26.firebasestorage.app',
    measurementId: 'G-E645T1CMGW',
  );
}
